import { useEffect, useMemo, useState } from 'react';
import {
  AlertTriangle, ChevronRight, Clock, ExternalLink, FileText,
  Receipt, ShieldCheck, ShoppingCart, Trash2, X,
} from 'lucide-react';
import { differenceInDays, format, parseISO } from 'date-fns';
import { Button } from '../../../components/ui/button';
import { Input } from '../../../components/ui/input';
import { Badge } from '../../../components/ui/badge';
import {
  useGanttSideStore, useOrdersForProject, useInvoices,
} from '../store';
import type { Warranty } from '../types';

interface WarrantyDrawerProps {
  warranty: Warranty | null;
  isOpen: boolean;
  onClose: () => void;
  projectId: string;
  readOnly?: boolean;
  canDelete?: boolean;
}

function healthOf(w: Warranty): 'expired' | 'expiring' | 'active' {
  const days = differenceInDays(parseISO(w.expiryDate), new Date());
  if (days < 0)  return 'expired';
  if (days < 90) return 'expiring';
  return 'active';
}

const HEALTH_TONE: Record<'active' | 'expiring' | 'expired', string> = {
  active:   'border-emerald-200 bg-emerald-50 text-emerald-700',
  expiring: 'border-amber-200 bg-amber-50 text-amber-700',
  expired:  'border-red-200 bg-red-50 text-red-700',
};

const HEALTH_LABEL: Record<'active' | 'expiring' | 'expired', string> = {
  active:   'Active',
  expiring: 'Expiring soon',
  expired:  'Expired',
};

export default function WarrantyDrawer({
  warranty, isOpen, onClose, projectId, readOnly = false, canDelete = true,
}: WarrantyDrawerProps) {
  const updateWarranty = useGanttSideStore((s) => s.updateWarranty);
  const removeWarranty = useGanttSideStore((s) => s.removeWarranty);
  const orders   = useOrdersForProject(projectId);
  const invoices = useInvoices(projectId);

  const [draft, setDraft] = useState<Partial<Warranty>>({});
  const [confirmDelete, setConfirmDelete] = useState(false);

  useEffect(() => {
    if (!isOpen || !warranty) return;
    setDraft({
      description: warranty.description,
      supplierName: warranty.supplierName,
      startDate: warranty.startDate,
      expiryDate: warranty.expiryDate,
      fileRef: warranty.fileRef,
      notes: warranty.notes,
    });
    setConfirmDelete(false);
  }, [isOpen, warranty?.id]);

  if (!isOpen || !warranty) return null;

  const order   = orders.find((o)   => o.id === warranty.orderId);
  const invoice = invoices.find((i) => i.id === warranty.invoiceId);
  const lineItem = order?.lineItems.find((l) => l.id === warranty.lineItemId);
  const isAutoGenerated = !!warranty.invoiceId && !!warranty.orderId;
  const health = healthOf(warranty);
  const expiryDays = differenceInDays(parseISO(warranty.expiryDate), new Date());

  const commitField = <K extends keyof Warranty>(key: K, value: Warranty[K]) => {
    setDraft((d) => ({ ...d, [key]: value }));
    if (warranty[key] === value) return;
    updateWarranty(projectId, warranty.id, { [key]: value } as Partial<Warranty>);
  };

  return (
    <>
      <div
        className="fixed inset-0 z-40 bg-slate-900/40 backdrop-blur-sm"
        onClick={onClose}
      />
      <aside
        className="fixed inset-x-0 bottom-0 z-50 flex max-h-[92vh] flex-col rounded-t-2xl bg-white shadow-2xl sm:inset-y-0 sm:right-0 sm:left-auto sm:max-h-none sm:w-[480px] sm:rounded-l-2xl sm:rounded-tr-none lg:w-[560px]"
        role="dialog"
        aria-modal="true"
      >
        {/* Mobile drag handle */}
        <div className="flex justify-center pt-2 sm:hidden">
          <span className="h-1 w-10 rounded-full bg-slate-300" />
        </div>

        {/* Header */}
        <header className="flex items-start justify-between gap-3 border-b border-slate-100 px-5 py-4">
          <div className="min-w-0 flex-1">
            <p className="text-[10px] font-medium uppercase tracking-[0.2em] text-slate-500">
              Warranty
            </p>
            <input
              value={draft.description ?? ''}
              onChange={(e) => setDraft((d) => ({ ...d, description: e.target.value }))}
              onBlur={() => commitField('description', (draft.description ?? '').trim() || warranty.description)}
              disabled={readOnly}
              placeholder="What's covered…"
              className="mt-1 w-full border-0 bg-transparent text-base font-semibold text-slate-900 placeholder:text-slate-300 focus:outline-none"
            />
            <input
              value={draft.supplierName ?? ''}
              onChange={(e) => setDraft((d) => ({ ...d, supplierName: e.target.value }))}
              onBlur={() => commitField('supplierName', (draft.supplierName ?? '').trim())}
              disabled={readOnly}
              placeholder="Supplier"
              className="mt-1 w-full border-0 bg-transparent text-sm text-slate-600 placeholder:text-slate-300 focus:outline-none"
            />
          </div>
          <div className="flex flex-col items-end gap-2">
            <button
              type="button"
              onClick={onClose}
              className="flex h-9 w-9 items-center justify-center rounded-md text-slate-400 hover:bg-slate-100 hover:text-slate-600"
              aria-label="Close"
            >
              <X className="h-4 w-4" />
            </button>
            <Badge variant="outline" className={`text-[10px] uppercase tracking-wider ${HEALTH_TONE[health]}`}>
              {HEALTH_LABEL[health]}
            </Badge>
          </div>
        </header>

        {/* Body */}
        <div className="min-h-0 flex-1 overflow-y-auto p-5">
          {/* Source banner */}
          {isAutoGenerated && (
            <div className="mb-5 rounded-lg border border-blue-200 bg-blue-50 p-3 text-xs text-blue-800">
              <p className="flex items-center gap-1.5 font-medium">
                <ShieldCheck className="h-3.5 w-3.5" />
                Auto-generated from a paid invoice
              </p>
              <p className="mt-1 text-[11px] text-blue-700">
                Edit the description and expiry directly here. The link to the
                source invoice and order is preserved below.
              </p>
            </div>
          )}

          {/* Coverage period */}
          <section className="mb-6">
            <h3 className="mb-3 text-[11px] font-medium uppercase tracking-[0.2em] text-slate-500">
              Coverage period
            </h3>
            <div className="grid grid-cols-2 gap-3">
              <Field label="Starts">
                <Input
                  type="date"
                  value={draft.startDate ?? ''}
                  onChange={(e) => setDraft((d) => ({ ...d, startDate: e.target.value }))}
                  onBlur={(e) => commitField('startDate', e.target.value)}
                  disabled={readOnly}
                />
              </Field>
              <Field label="Expires">
                <Input
                  type="date"
                  value={draft.expiryDate ?? ''}
                  onChange={(e) => setDraft((d) => ({ ...d, expiryDate: e.target.value }))}
                  onBlur={(e) => commitField('expiryDate', e.target.value)}
                  disabled={readOnly}
                />
              </Field>
            </div>
            <p className={`mt-2 text-xs ${
              health === 'expired'  ? 'text-red-600' :
              health === 'expiring' ? 'text-amber-600' :
                                      'text-slate-500'
            }`}>
              {health === 'expired'  && <><AlertTriangle className="mr-1 inline h-3 w-3" /> Expired {Math.abs(expiryDays)} day{Math.abs(expiryDays) === 1 ? '' : 's'} ago</>}
              {health === 'expiring' && <><Clock         className="mr-1 inline h-3 w-3" /> Expires in {expiryDays} day{expiryDays === 1 ? '' : 's'}</>}
              {health === 'active'   && <>Valid for {expiryDays} more days</>}
            </p>
          </section>

          {/* Linked records */}
          {(order || invoice || lineItem) && (
            <section className="mb-6">
              <h3 className="mb-3 text-[11px] font-medium uppercase tracking-[0.2em] text-slate-500">
                Source records
              </h3>
              <div className="space-y-2">
                {order && (
                  <LinkRow
                    icon={ShoppingCart}
                    label="Order"
                    primary={order.poNumber}
                    secondary={
                      lineItem
                        ? `Line: ${lineItem.description}`
                        : `${order.lineItems.length} line${order.lineItems.length === 1 ? '' : 's'}`
                    }
                  />
                )}
                {invoice && (
                  <LinkRow
                    icon={Receipt}
                    label="Invoice"
                    primary={invoice.invoiceNumber}
                    secondary={
                      invoice.paidDate
                        ? `Paid ${format(parseISO(invoice.paidDate), 'MMM d, yyyy')}`
                        : 'Pending'
                    }
                  />
                )}
              </div>
            </section>
          )}

          {/* Document reference */}
          <section className="mb-6">
            <h3 className="mb-3 text-[11px] font-medium uppercase tracking-[0.2em] text-slate-500">
              Document
            </h3>
            <Field label="File reference (optional)">
              <Input
                value={draft.fileRef ?? ''}
                onChange={(e) => setDraft((d) => ({ ...d, fileRef: e.target.value }))}
                onBlur={(e) => commitField('fileRef', e.target.value)}
                disabled={readOnly}
                placeholder="Drive link or filename for the warranty PDF"
              />
            </Field>
            {warranty.fileRef && (
              <p className="mt-2 inline-flex items-center gap-1.5 text-[11px] text-slate-500">
                <FileText className="h-3 w-3" />
                {warranty.fileRef}
              </p>
            )}
          </section>

          {/* Notes */}
          <section>
            <h3 className="mb-3 text-[11px] font-medium uppercase tracking-[0.2em] text-slate-500">
              Notes
            </h3>
            <textarea
              value={draft.notes ?? ''}
              onChange={(e) => setDraft((d) => ({ ...d, notes: e.target.value }))}
              onBlur={(e) => commitField('notes', e.target.value)}
              disabled={readOnly}
              rows={3}
              placeholder="Coverage scope, claim contacts, exclusions…"
              className="block w-full rounded-md border border-slate-200 px-3 py-2 text-sm shadow-sm focus:border-emerald-500 focus:outline-none focus:ring-1 focus:ring-emerald-500 disabled:bg-slate-50"
            />
          </section>
        </div>

        {/* Footer */}
        <footer className="flex flex-shrink-0 items-center justify-between gap-3 border-t border-slate-100 px-5 py-3">
          <span className="text-[11px] text-slate-400">
            {readOnly ? 'Read-only' : 'Auto-saves on blur'}
          </span>
          {!readOnly && canDelete && (
            confirmDelete ? (
              <div className="flex items-center gap-2">
                <span className="text-xs text-red-600">Delete this warranty?</span>
                <Button variant="outline" size="sm" onClick={() => setConfirmDelete(false)}>Cancel</Button>
                <button
                  type="button"
                  onClick={() => { removeWarranty(projectId, warranty.id); onClose(); }}
                  className="inline-flex items-center gap-1.5 rounded-md bg-red-600 px-3 py-1.5 text-xs font-medium text-white hover:bg-red-700"
                >
                  <Trash2 className="h-3.5 w-3.5" />
                  Confirm
                </button>
              </div>
            ) : (
              <button
                type="button"
                onClick={() => setConfirmDelete(true)}
                className="inline-flex items-center gap-1.5 rounded-md px-3 py-1.5 text-xs font-medium text-slate-500 hover:bg-red-50 hover:text-red-600"
              >
                <Trash2 className="h-3.5 w-3.5" />
                Delete
              </button>
            )
          )}
        </footer>
      </aside>
    </>
  );
}

// ─── Helpers ───────────────────────────────────────────────────────────────

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label className="block">
      <span className="mb-1 block text-xs font-medium text-slate-600">{label}</span>
      {children}
    </label>
  );
}

function LinkRow({
  icon: Icon, label, primary, secondary,
}: {
  icon: typeof Receipt;
  label: string;
  primary: string;
  secondary: string;
}) {
  return (
    <div className="flex items-start gap-3 rounded-lg border border-slate-200 bg-white p-3">
      <div className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-md bg-slate-50">
        <Icon className="h-3.5 w-3.5 text-slate-500" />
      </div>
      <div className="min-w-0 flex-1">
        <p className="text-[10px] font-medium uppercase tracking-wider text-slate-500">{label}</p>
        <p className="font-mono text-sm text-slate-900">{primary}</p>
        <p className="mt-0.5 text-[11px] text-slate-500">{secondary}</p>
      </div>
    </div>
  );
}